### ISSUE TITLE
Fatal Error after updating plugin simplenavi

### ISSUE THREAD

**Issue by thomas2de** [cosmocode/simplenavi#34]
Hi,
I use Dokuwiki since ca. 6 years.
And i like the plugin simplenavi, because it makes the navigation so much easy.
Thank you so far.
My Dokuwiki runs in a Synology NAS and it is kept uptodate automaticly.
Now I found out, that some of my plugins need an update manualy.
After updating the plugins (the newest update was simplenavi) I get an error-stack shown in the sidebar, where simplenavi used to be present:
The error-stack:
` Fatal error: Uncaught Error: Class 'dokuwiki\File\PageResolver' not found in /volume1/web/dokuwiki/lib/plugins/simplenavi/syntax.php:163 Stack trace: #0 /volume1/web/dokuwiki/inc/search.php(59): syntax_plugin_simplenavi->cbSearch(Array, '/var/services/w...', '/linux', 'd', 1, Array) #1 /volume1/web/dokuwiki/lib/plugins/simplenavi/syntax.php(66): search(Array, '/var/services/w...', Array, Array, '/linux', 1, 'natural') #2 /volume1/web/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_simplenavi->render('xhtml', Object(Doku_Renderer_xhtml), Array) #3 /volume1/web/dokuwiki/inc/parserutils.php(673): Doku_Renderer->plugin('simplenavi', Array, 5, '{{simplenavi>}}') #4 /volume1/web/dokuwiki/inc/parserutils.php(142): p_render('xhtml', Array, NULL) #5 /volume1/web/dokuwiki/inc/parserutils.php(89): p_cached_output('/var/services/w...', 'xhtml', 'sidebar') #6 /volume1/web/dokuwiki/inc/template.php(1580): p_wiki_xhtml('sidebar', '', false) #7 /volume1/web/dokuwiki/lib/tpl/dokuwiki/main.php(42): tpl_include_page('sidebar', true, tr in /volume1/web/dokuwiki/lib/plugins/simplenavi/syntax.php on line 163 ` 

Can you help me, please?

**Comment by splitbrain** [comment]
Seems like you updated the plugin but not your wiki. The plugin is not compatible with old DokuWiki versions anymore. Either update your wiki (recommended) or downgrade the plugin to an earlier release: https://github.com/cosmocode/simplenavi/tags

**Comment by thomas2de** [comment]
thanks for the fast response and hint.
The package manager of my NAS offers Dokuwiki only in Version 2020 Hogfather.
So I downgraded simplenavi - and my wiki runs again.
